project:
  type: website

website: 
  title: RSTbx
  page-navigation: true
  navbar: 
    left:
      - file: index.qmd
        text: Getting Started
      - text: Tutorials
        menu:
          - href: tutorial/1_pop_data.qmd
          - href: tutorial/2a_indiv_event_data.qmd
          - href: tutorial/2b_agg_event_data.qmd
          - href: tutorial/3_stab_rates.qmd
      - file: reference/index.qmd
        text: Reference

format:
  html:
    theme: cosmo
    toc: true
