---
title: 3. Producing Stabilized Rates
bibliography: model_citations.bib
---

The final step of a RSTbx workflow is producing stabilized rates!

## Model

The Univariate Conditional Autoregressive (UCAR) model used by RSTbx is based on the model developed by @besag_bayesian_1991 with modifications using inverse transform sampling for restricted informativeness based on @quick_evaluating_2021:

$$
\begin{split}
Y_{i} &\sim \text{Binomial}(n_{i}, \theta_{i}) \\ 
\theta_{i} &\sim \text{LogitNormal}(\beta_{j} + Z_{i}, \tau^2), \\ 
i &=\{1,...,N_s\}, j =\{1,...,N_{is}\}
\end{split}
$$

$$
\begin{split}
\beta_{j} &\sim \text{Normal}(0,\sigma_{\beta}^2),\ \sigma_{\beta}^2 \to \infty \\
Z &\sim \text{CAR}(\sigma^2) \\
\sigma^2 &\sim \text{InvGamma}(a_\sigma,b_\sigma) \\
\tau^2 &\sim \text{InvGamma}(a_\tau,b_\tau)
\end{split}
$$

Additional models are available within the [RSTr package](https://cehi-code-repos.github.io/RSTr/).

## Requirements

### Aggregate event and population table

Aggregate event and population tables should be formated to have one record (aka row) for each
region. It would look something like:

|GEOID | EventCount| PopulationCount|
|:-----|----------:|---------------:|
|01001 |          0|            3430|
|01001 |          1|            7749|
|01001 |          0|            7339|
|...   |        ...|             ...|
|72153 |          5|            4527|
|72153 |          7|            3223|
|72153 |          9|             571|


If you would like to produce age-adjusted rates, aggregate event tables should
have one record (aka row) for reach region-age group combination. Like this:

|GEOID |AgeGroup | EventCount| PopulationCount|
|:-----|:--------|----------:|---------------:|
|01001 |0-4      |          0|            3430|
|01001 |5-14     |          1|            7749|
|01001 |15-24    |          0|            7339|
|...   |...      |        ...|             ...|
|72153 |65-74    |          5|            4527|
|72153 |75-84    |          7|            3223|
|72153 |85up     |          9|             571|

### Boundary File

See [1. Acquiring Population Data - Boundary File](1_pop_data.qmd#boundary-file)

## Usage

### Producing crude rates

If you haven't already, [set up](../index.qmd#set-up) the Rate Stabilizing Toolbox.

1.  Open up the **Catalog Pane**.

2.  Right click on **Databases**, select **Add Database**, and navigate to where you have downloaded and extracted 
    the RSTbx and find *data.gdb*.

3.  Within the *data.gdb*, right click on *mi_carto* and *mi_joined_event_pop*, and **Add to Current Map**.

4.  Open the **Rate Stabilizing Tool**  

5.  Set the following parameters and **Run**:
    
    **Input Table**: data.gdb/mi_joined_event_pop  
    **Input Table Fields**:  
    -   **Region ID**: GEOID  
    -   **Event Count**: EventCount  
    -   **Population Count**: PopulationCount  

    **Input Feature**: data.gdb/mi_carto  
    **Input Feature Fields**:  
    -   **Region ID**: GEOID  

    **Additional Options**:  
    -   **Credible Level**: 0.95  
    -   **Rate Per**: 100,000  
    -   **Number of Years**: 1  

    **Output Table**: crude_rates  
    **Age Group Field**: Leave blank  
    **Standard Population Year**: Leave blank  
    **Standardized Age Groups**:  
    -   **Lower age group**: Leave blank  
    -   **Upper age group**: Leave blank  

### Producing age-adjusted rates

1.  Within the *data.gdb*, right click on *mi_joined_event_pop_strat*, and **Add to Current Map**.  

2.  Returning back to the **Rate Stabilizing Tool**, set the following parameters and **Run**:
    
    **Input Table**: data.gdb/mi_joined_event_pop_strat  
    **Input Table Fields**:  
    -   **Region ID**: GEOID  
    -   **Event Count**: EventCount  
    -   **Population Count**: PopulationCount  

    **Input Feature**: data.gdb/mi_carto  
    **Input Feature Fields**:  
    -   **Region ID**: GEOID  

    **Additional Options**:  
    -   **Credible Level**: 0.95  
    -   **Rate Per**: 100,000  
    -   **Number of Years**: 1  

    **Output Table**: age_adj_rate  
    **Age Group Field**: AgeGroup   
    **Standard Population Year**: 2010  
    **Standardized Age Groups**:  
    -   **Lower age group**: 35, 64, 34  
    -   **Upper age group**: 64, up, up  
